---
version: "3"
desc: "Build and test docker release assets"

vars:
  image: titpetric/task-ui
  root:
    sh: git rev-parse --show-toplevel || echo .

tasks:
  build:
    desc: "Build task-ui docker image"
    dir: '{{ .root }}'
    cmds:
      - docker build --build-arg ssh_private_key="$(cat ./.ssh/id_rsa)" -t {{ .image }} -f docker/Dockerfile --squash .
      - docker images | grep {{ .image }}

  gen:
    desc: "Generate ssh key for docker image"
    dir: '{{ .root }}/docker'
    cmds:
      - ssh-keygen -t ecdsa -f ./root/.ssh/id_ecdsa -C task-ui
      - cat ./root/.ssh/id_ecdsa.pub

  run:
    desc: "Run task-ui in docker env"
    dir: '{{ .root }}/docker'
    cmds:
      - docker compose up

  push:
    desc: "Push task-ui to registry"
    cmds:
      - docker push {{ .image }}
